Initialize project with linter and empty Maven project
googleinterns/step145-2020 pull request #4
Opened 2020-06-25 18:22 UTC by ramyabuva

2020-06-25 20:38 UTC, savsa requested changes

2020-06-25 20:38 UTC, savsa commented on capstone/pom.xml
> +          <deploy.projectId>YOUR_PROJECT_ID_HERE</deploy.projectId>
I think we can already use the project ID they gave us: `step-team-145`

2020-06-26 16:44 UTC, savsa approved these changes

2020-06-26 17:22 UTC, wli approved these changes

2020-06-26 17:22 UTC, wli commented on pom.xml
> +          <!-- TODO: set project ID. -->
remove the TODO

2020-06-26 20:38 UTC, triplehair approved these changes

2020-06-26 20:41 UTC, merged